Don't exit the scheduler even when there are only jobs without any schedules
Icinga/icingaweb2-module-x509 pull request #112
Opened 2022-07-25 17:00 UTC by yhabteab

Im Moment ist es ja so, dass wenn die configs einmal gelesen und wenn die entsprechende schedule crontab beinhalten, werden zu den scheduler hinzugefügt. Wenn aber keine einzige Jobs existiert, die die Attribute schedule gesetzt hat, wird der scheduler sofort beendet und wird nie wieder gestartet. Diese PR fixt dies, in dem es ein config watchdog job dem scheduler übergibt, welche alle eine 1 Stunde überprüft, ob die job configs was geändert hat und wenn so, den scheduler auffordert sich zu stoppen und die configs neu zu vom Disk zu laden.

fixes #35

2022-07-26 14:20 UTC, nilmerg reviewed
Not bad? Though, I wonder why there isn't a single watchdog that's running the entire time. This could also spawn newly added jobs, what the current solution cannot.

2022-07-26 17:11 UTC, yhabteab commented
> Though, I wonder why there isn't a single watchdog that's running the entire time.

Well, I was thinking that when adding new jobs, the user should restart the systemd service manually! However, if that' s not acceptable to you, I could add such a watchdog as well.

2022-07-27 06:26 UTC, nilmerg commented
> Well, I was thinking that when adding new jobs, the user should restart the systemd service manually!

Why should that be of advantage or necessary? I'd personally expect a service to respect configuration changes automatically. That's dependent on the nature of the service however, Icinga 2 shouldn't do that, but Icinga Web does for instance. This service here scans the network, what harm could it made if jobs are scheduled/run automatically? Except that incorrectly configured jobs do as well, I can't think of any.

But @lippserd may object, wait for his review.

2022-07-28 07:56 UTC, lippserd requested changes
A separate task that continuously checks the configuration for changes sounds good to me!

2022-08-26 12:34 UTC, yhabteab commented
Requires: https://github.com/Icinga/ipl-scheduler/pull/1

2022-10-25 15:07 UTC, lippserd requested changes
There's more to come, but I'd like to discuss that with you tomorrow.

2022-10-26 07:56 UTC, lippserd requested changes

2022-10-26 07:56 UTC, lippserd commented on application/clicommands/ScanCommand.php
> +            Logger::error(sprintf(
Use the same log message as in `attachJobsLogging()`.

2022-10-26 07:56 UTC, lippserd commented on application/clicommands/ScanCommand.php
> +            Logger::info(sprintf('Scanned %s target(s) in job %s', $targets, $job->getName()));
> Scanned `%d` ... from job ...

2022-10-26 07:56 UTC, lippserd commented on application/clicommands/JobsCommand.php
> +            Logger::info('Task %s successfully finished: %s', $task->getName(), $output);
Use the same log message as in the `ScanCommand`.

2022-10-26 07:56 UTC, lippserd commented on library/X509/Job.php
> +            if ($this->finishedTargets === 0) {
Remove the entire code block and verify the certificates in the cli commands.

2022-10-26 07:56 UTC, lippserd commented on library/X509/Job.php
> +            $this->deferred->resolve($this->totalTargets);
Resolve with `finishedTargets`.

2022-10-26 07:56 UTC, lippserd commented on library/X509/Job.php
> +                Logger::warning('The job %s does not have any targets', $this->getName());
Remove the log message. Should be done in the cli commands.

2022-10-26 08:28 UTC, lippserd requested changes

2022-10-26 08:28 UTC, lippserd commented on library/X509/Job.php
> +        $this->deferred = new Promise\Deferred(function () {
What about `$promise->always(updateJobStats(true));` Then you can remove the other calls and adjust the method signature.

2022-10-26 14:08 UTC, yhabteab commented on application/clicommands/JobsCommand.php
> +            Loop::addTimer(30, $watchdog);
🐘

2022-10-26 15:40 UTC, lippserd requested changes

2022-10-27 07:20 UTC, yhabteab commented on application/clicommands/ScanCommand.php
> +            // Reset registered signals not to block the event loop indefinitely
Ahh 😌, not totally! But since I am going to use a `Loop::stop()` there, it doesn't matter. So will remove it.

2022-10-27 09:16 UTC, lippserd requested changes

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/JobsCommand.php
> +                    'Removing scheduled job %s, as it either no longer exists in the configuration or its config has' .
In such cases, don't we put the string concat operator on the next line? Please remove the dot at the end of the string. We had the discussion a few days ago that we don't want to end log messages with a punctuation mark.

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/JobsCommand.php
Remove the newline here please.

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/ScanCommand.php
Remove the newline here please.

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/ScanCommand.php
Remove the newline here please.

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/ScanCommand.php
Remove the newline here please.

2022-10-27 09:16 UTC, lippserd commented on application/clicommands/JobsCommand.php
> +                    Logger::error('Invalid cron expression provided: %s', $schedule);
> Job %s has invalid schedule expression %

2022-10-27 09:44 UTC, lippserd approved these changes
🚀

2022-10-27 09:44 UTC, merged