Allow to exclude specific targets from scans
Icinga/icingaweb2-module-x509 pull request #118
Opened 2022-09-15 14:46 UTC by yhabteab

resolves #11

2022-09-22 06:32 UTC, lippserd requested changes

2022-09-22 06:32 UTC, lippserd commented on library/X509/Job.php
> +                    Logger::info("Excluding IP '$ip' from scan target");
Remove quotes around IP and remove the word target. I also would set the level to debug.

2022-09-27 12:06 UTC, yhabteab commented
### Blocked by
- https://github.com/Icinga/icingaweb2-module-x509/pull/114

2022-11-07 11:13 UTC, lippserd approved these changes

2022-11-07 11:15 UTC, merged