Provide job schedules widget
Icinga/icingaweb2-module-x509 pull request #122
Opened 2022-09-20 09:51 UTC by yhabteab

resolves #46

2022-09-21 15:16 UTC, yhabteab commented
### Requires

- `"dragonmantank/cron-expression": "^3.3.1"`

2023-02-20 16:42 UTC, nilmerg commented
Things I noticed during testing the schedule element:

* You're still saving frequencies incorrectly here. (You're not calling `json_encode` yourself)
* Trying to update an existing job fails
  * The error message contains a typo: `Filed to update job...`

2023-02-21 08:45 UTC, yhabteab commented
> Trying to update an existing job fails

Can you be a little more precise? This doesn't say anything about why the job update fails. I'm unable able to reproduce it.

2023-02-21 15:41 UTC, nilmerg commented
Editing the end time of an existing job fails with the complaint *that a section "name" already exists*.

2023-02-21 15:52 UTC, yhabteab commented
> Editing the end time of an existing job fails with the complaint _that a section "name" already exists_.

This can only be the case when you're trying to create a job with the same name, but never when editing it. Please check the urls in the search bar.

2023-02-27 12:46 UTC, yhabteab commented
> Editing the end time of an existing job fails with the complaint _that a section "name" already exists_.

This is not only due to the new changes, but rather because the `INI` parser cannot handle **numeric** job names properly and is reproducible without this PR.
![Bildschirm­foto 2023-02-27 um 13 42 48](https://user-images.githubusercontent.com/57616252/221566812-34a96fa2-e32c-4577-985d-dc1184299ec3.png)

2023-04-04 13:34 UTC, nilmerg requested changes

2023-04-04 13:34 UTC, nilmerg commented on application/forms/Config/JobConfigForm.php
> +        }
Is this still required?

2023-04-04 13:34 UTC, nilmerg commented on application/forms/Config/JobConfigForm.php
> +    protected $identifier;
Please add a docstring.

2023-04-04 14:40 UTC, yhabteab commented on application/forms/Config/JobConfigForm.php
> +        }
Nope!

2023-04-04 15:13 UTC, nilmerg approved these changes

2023-04-04 15:32 UTC, merged