Change all `timestamp` columns to `bigint` & adjust all usages
Icinga/icingaweb2-module-x509 pull request #138
Opened 2022-11-04 16:58 UTC by yhabteab

2022-11-07 16:01 UTC, yhabteab commented
### Blocked by

- https://github.com/Icinga/icingaweb2-module-x509/pull/114

2023-01-30 14:37 UTC, lippserd requested changes
Please rebase.

2023-02-06 12:11 UTC, lippserd requested changes
In addition to the changes requested please also remove the `UNIX_TIMESTAMP_MILLI` database functions.

2023-02-08 08:13 UTC, lippserd approved these changes

2023-02-08 08:13 UTC, merged