Controller: Remove custom `getDb()` method
Icinga/icingaweb2-module-x509 pull request #152
Opened 2023-02-22 10:35 UTC by yhabteab

2023-02-22 10:36 UTC, yhabteab commented
@cla-bot check

2023-02-23 09:39 UTC, lippserd requested changes
Please let the commit (and PR) explain why this is no longer necessary.

2023-02-23 10:40 UTC, lippserd requested changes
I would precise commit message and description (also PR title and description then) to the following:

> Remove `Controller::getDb()` override
>
> Now that we're using `ipl\Orm` everywhere, there's no need to set the fetch mode to anything other than `PDO::FETCH_OBJ`.

2023-02-23 10:58 UTC, lippserd approved these changes

2023-02-23 10:58 UTC, merged