Recommend to install from packages
Icinga/icingaweb2-module-x509 pull request #168
Opened 2023-04-04 22:16 UTC by lippserd

2023-04-05 07:16 UTC, nilmerg submitted a review, later dismissed

2023-04-05 07:17 UTC, nilmerg approved these changes

2023-04-05 11:53 UTC, yhabteab approved these changes

2023-04-05 11:59 UTC, nilmerg submitted a review, later dismissed

2023-04-05 12:19 UTC, yhabteab submitted a review, later dismissed

2023-04-11 12:36 UTC, nilmerg requested changes

2023-04-11 12:36 UTC, nilmerg commented on doc/02-Installation.md
> +<!-- {% endif %} -->
I hope users are not that oblivious that we need to repeat this 10 lines later again.

2023-04-11 12:36 UTC, nilmerg commented on doc/02-Installation.md
> +<!-- {% endif %} -->
Same here

2023-04-12 06:39 UTC, nilmerg approved these changes

2023-04-12 06:39 UTC, merged