Support import sourt source with postgresql
Icinga/icingaweb2-module-x509 pull request #95
Opened 2021-03-25 13:55 UTC by raviks789

Earlier import source was not working because of the grouping function. Here this has been fixed.

2021-03-26 09:18 UTC, nilmerg requested changes
There's also the `ServicesImportSource` which may also be subject to this issue. Please change this as well.

2021-03-26 09:18 UTC, nilmerg commented on library/X509/ProvidedHook/HostsImportSource.php
> +        }
Please duplicate less code here. You can for example do the following:

```php
$targets = (new ...)->from(...);

if ($postgres) {
    $targets->columns(...);
} else {
    $targets->columns(...);
}

$targets->join(...)
    ->join(...)
    ->...;

```

2021-03-26 09:18 UTC, nilmerg commented on library/X509/ProvidedHook/HostsImportSource.php
> +            }
Please add an empty line after closing braces.

2021-03-26 09:18 UTC, nilmerg commented on library/X509/ProvidedHook/HostsImportSource.php
> -        $results = [];
Please re-add this. It's still in use after all.

2021-04-30 12:34 UTC, nilmerg requested changes
Tested it now myself successfully. Results from MySQL and PostgreSQL are identical for me, so it works fine as it should! :+1: 

But please apply the changes I've requested, now two additional ones.

2021-04-30 12:34 UTC, nilmerg commented on library/X509/ProvidedHook/ServicesImportSource.php
> +                        ->from(['x509_certificate_subject_alt_name can'])
The array here is redundant. That the implementation of `from()` does it isn't a reason why we should do it here. Please undo this change.

2021-04-30 12:34 UTC, nilmerg commented on library/X509/ProvidedHook/ServicesImportSource.php
> +            }
Please also add an empty line after this closing brace.

2021-04-30 12:43 UTC, nilmerg commented
And please rebase with master. This then ensures the CI checks will run.

2022-07-04 09:45 UTC, lippserd commented
Should be pushed to #85.

2022-07-05 08:19 UTC, raviks789 commented
> Should be pushed to #85.

The changes have been pushed to #85

2022-07-05 08:19 UTC, closed without merging